CREATE OR REPLACE PROCEDURE `planify_add_change`
(
    IN p_GID INT UNSIGNED,
	IN p_P_DAY SMALLINT UNSIGNED,
	IN p_P_HOUR SMALLINT UNSIGNED,
	IN p_P_TARGET NUMERIC(3,1) 
)
BEGIN 
    INSERT INTO Planify VALUES (p_GID, p_P_DAY, p_P_HOUR, p_P_TARGET);
END