CREATE USER 'webclient'@'localhost' IDENTIFIED BY 'webconnect';
CREATE USER 'espclient'@'localhost' IDENTIFIED BY 'espconnect';

GRANT ALL PRIVILEGES ON * . * TO 'webclient'@'localhost';
GRANT ALL PRIVILEGES ON * . * TO 'espclient'@'localhost';

CREATE DATABASE TempSystem;
USE TempSystem;

CREATE TABLE Rooms(
    GID INT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
    TempTarget  NUMERIC(3,1) NOT NULL,
    Name VARCHAR(50) NOT NULL,
    Sensor VARCHAR(10) UNIQUE,
	ProgEnable BOOL DEFAULT FALSE
);

CREATE TABLE Sensors( 
    SID VARCHAR(10) NOT NULL UNIQUE, 
    Value  NUMERIC(3,1) NOT NULL, 
    LastUpdate DATETIME NOT NULL 
);

CREATE TABLE Regulators( 
    RID VARCHAR(10) NOT NULL UNIQUE, 
    LastUpdate DATETIME NOT NULL  
);

CREATE TABLE RegulatorsLinks(
    GID INT UNSIGNED NOT NULL,
    RID VARCHAR(10) NOT NULL UNIQUE
);

CREATE TABLE Windows( 
    WID VARCHAR(10) NOT NULL UNIQUE, 
	State BOOL NOT NULL,
    LastUpdate DATETIME NOT NULL  
);

CREATE TABLE WindowsLinks(
    GID INT UNSIGNED NOT NULL,
    WID VARCHAR(10) NOT NULL UNIQUE
);

CREATE TABLE SensorsHistory(
    SID VARCHAR(10) NOT NULL,
    Value NUMERIC(3,1) NOT NULL,
    VTime DATETIME NOT NULL
);

CREATE TABLE Settings(
	S_KEY VARCHAR(100) NOT NULL UNIQUE,
	S_VALUE VARCHAR(100) 
);

INSERT INTO Settings VALUES
	("Name", "Inconnu"),
	("Password", "13d8c9009647abffee45341993ab3952f57c361d"),
	("Localisation", "lat=0&lon=0");

CREATE TABLE Planify(
	GID INT UNSIGNED NOT NULL,
	P_DAY SMALLINT UNSIGNED NOT NULL,
	P_HOUR SMALLINT UNSIGNED NOT NULL,
	P_TARGET NUMERIC(3,1) NOT NULL
);

ALTER TABLE Rooms 
ADD CONSTRAINT fk_SID 
    FOREIGN KEY (Sensor) 
    REFERENCES Sensors(SID) 
    ON DELETE CASCADE 
    ON UPDATE CASCADE;

ALTER TABLE RegulatorsLinks 
ADD CONSTRAINT fk_RID 
    FOREIGN KEY (RID) 
    REFERENCES Regulators(RID) 
    ON DELETE CASCADE 
    ON UPDATE CASCADE;
	
ALTER TABLE RegulatorsLinks 
ADD CONSTRAINT fk_GID 
    FOREIGN KEY (GID) 
    REFERENCES Rooms(GID) 
    ON DELETE CASCADE 
    ON UPDATE CASCADE;

ALTER TABLE SensorsHistory 
ADD CONSTRAINT fk_SID_History
    FOREIGN KEY (SID) 
    REFERENCES Sensors(SID) 
    ON DELETE CASCADE 
    ON UPDATE CASCADE;
	
ALTER TABLE WindowsLinks
ADD CONSTRAINT fk_GID_WL
    FOREIGN KEY (GID) 
    REFERENCES Rooms(GID) 
    ON DELETE CASCADE 
    ON UPDATE CASCADE;
	
ALTER TABLE WindowsLinks
ADD CONSTRAINT fk_WID_WL
    FOREIGN KEY (WID) 
    REFERENCES Windows(WID) 
    ON DELETE CASCADE 
    ON UPDATE CASCADE;

ALTER TABLE Planify
ADD CONSTRAINT fk_GID_Planify
	FOREIGN KEY (GID) 
    REFERENCES Rooms(GID) 
    ON DELETE CASCADE 
    ON UPDATE CASCADE;

